### ISSUE TITLE
Include audio files in the repo

### ISSUE THREAD

**Issue by MilesBHuff** [Lastique/src_test#1]
Currently, users need to download each individual audio testfile from lastique.github.io.  It would be really convenient if you were to include these files in the repo proper.

**Comment by Lastique** [comment]
I don't want to duplicate binary data files in git. They are huge, and I'm not happy about making users download them when they only want to build the test. Having to download them twice and then moving them around as one checks out the source code makes it worse.

**Comment by MilesBHuff** [comment]
I figured that was your reasoning.  It's indeed true that binary files are not something that are generally kept under a VCS.  And those are fair points about filesizes.
Maybe you could add a .tar.xz to to .io site?
